# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: all.cmd
      shell: cmd

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: libarchive_Windows_x64_build
        path: |
          stage/bin/archive.dll
          stage/bin/bsd*.exe
          stage/version.txt

    # - name: Release
    #   uses: softprops/action-gh-release@v2
    #   with:
    #     body_path: stage/version.txt
