name: Main

on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64

    - name: Building zlib
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: zlib.cmd
      shell: cmd

    - name: Building bzip2
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: bzip2.cmd
      shell: cmd
    
    - name: Building xz
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: xz.cmd
      shell: cmd

    - name: Building zstd
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: zstd.cmd
      shell: cmd

    - name: Building libarchive
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: libarchive.cmd
      shell: cmd

    - name: Print versions
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: version.cmd
      shell: cmd

    - name: Compressing files
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: compress.cmd
      shell: cmd

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        token: ${{ secrets.RELEASETOKEN }}
        body_path: stage/version.txt
        files: stage/bin/libarchive_prebuilt_win_x64.tar.xz
