name: Main

on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v3
      with:
        msbuild-architecture: x64

    - name: Building zlib
      run: zlib.cmd
      shell: cmd

    - name: Building bzip2
      run: bzip2.cmd
      shell: cmd
    
    - name: Building xz
      run: xz.cmd
      shell: cmd

    - name: Building zstd
      run: zstd.cmd
      shell: cmd

    - name: Building libarchive
      run: libarchive.cmd
      shell: cmd

    - name: Print versions
      run: version.cmd
      shell: cmd

    - name: Compressing files
      run: compress.cmd
      shell: cmd

    - name: Release
      uses: softprops/action-gh-release@v3
      if: startsWith(github.ref, 'refs/tags/')
      with:
        token: ${{ secrets.RELEASETOKEN }}
        body_path: stage/version.txt
        files: stage/bin/libarchive_prebuilt_win_x64.zip
